import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    languageCode: 'en',
    diagnosisLabel: 'Analysis',
    adviceLabel: 'Recommendation',
    confidenceLabel: 'Model Confidence',
    appName: 'Geospatial AI',
    tagline: 'Ramgarh Engineering College - Ignition Ideators',
    welcome: 'Enhancing Indian agriculture using satellite imagery & Advanced AI (CNNs & Transformers)',
    dashboard: 'Dashboard',
    advisory: 'Yield & Flood Forecast',
    market: 'Real-time Monitoring',
    diagnosis: 'Crop Health (AI)',
    contact: 'Contact Ideators',
    signOut: 'Sign Out',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    location: 'Location',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    checkEmail: 'Please check your email for verification link',
    getStarted: 'Explore Data',
    learnMore: 'Project Details',
    features: 'Key Capabilities',
    aiAdvisory: 'Yield & Flood Forecasting',
    aiAdvisoryDesc: 'Utilizes Sentinel & RISAT data for flood decisions and yield prediction.',
    marketLinkage: 'Real-time Monitoring',
    marketLinkageDesc: 'Satellite imagery analysis for continuous field monitoring.',
    cropDiagnosis: 'Pest & Disease Detection',
    cropDiagnosisDesc: 'Advanced AI (CNNs) for detecting crop health issues and pests.',
    weatherInfo: 'Climate Resilience',
    weatherInfoDesc: 'Integrated soil pH indicator and climate resilience data.',
    advisoryHistory: 'Analysis History',
    addListing: 'Add Data Point',
    crop: 'Crop Type',
    quantity: 'Estimated Yield',
    unit: 'Unit',
    price: 'Market Value',
    save: 'Save Data',
    cancel: 'Cancel',
    getAdvice: 'Generate Forecast',
    season: 'Season/Period',
    uploadImage: 'Upload Satellite/Crop Image',
    submit: 'Analyze',
    diagnosing: 'Processing Imagery...',
    contactUs: 'Contact The Team',
    contactName: 'Name',
    contactMessage: 'Message',
    send: 'Send',
    dateLabel: 'Date',
    temperatureLabel: 'Temp',
    humidityLabel: 'Humidity',
    weatherLabel: 'Conditions',
    searchCity: 'Enter region',
    edit: 'Edit',
    delete: 'Delete',
    update: 'Update',
    loading: 'Loading Data...',
    search: 'Search Region',
    feelsLikeLabel: 'Soil Moisture',
    windLabel: 'Wind Speed',
    foggy: 'Low Visibility',
  },
  hi: {
    languageCode: 'hi',
    diagnosisLabel: 'विश्लेषण',
    adviceLabel: 'सिफारिश',
    confidenceLabel: 'मॉडल आत्मविश्वास',
    appName: 'Geospatial AI',
    tagline: 'रामगढ़ इंजीनियरिंग कॉलेज - इग्निशन आइडिएटर्स',
    welcome: 'उपग्रह इमेजरी और उन्नत एआई का उपयोग करके भारतीय कृषि को बढ़ाना',
    dashboard: 'डैशबोर्ड',
    advisory: 'उपज और बाढ़ पूर्वानुमान',
    market: 'वास्तविक समय निगरानी',
    diagnosis: 'फसल स्वास्थ्य (AI)',
    contact: 'संपर्क',
    signOut: 'साइन आउट',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    location: 'स्थान',
    alreadyHaveAccount: 'क्या आपके पास पहले से एक खाता मौजूद है?',
    dontHaveAccount: 'क्या आपके पास खाता नहीं है?',
    checkEmail: 'कृपया सत्यापन लिंक के लिए अपना ईमेल जांचें',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    features: 'विशेषताएं',
    aiAdvisory: 'उपज और बाढ़ पूर्वानुमान',
    aiAdvisoryDesc: 'बाढ़ के फैसलों और उपज की भविष्यवाणी के लिए सेंटिनल और RISAT डेटा का उपयोग करता है।',
    marketLinkage: 'वास्तविक समय निगरानी',
    marketLinkageDesc: 'निरंतर खेत की निगरानी के लिए उपग्रह इमेजरी विश्लेषण।',
    cropDiagnosis: 'कीट और रोग का पता लगाना',
    cropDiagnosisDesc: 'फसल स्वास्थ्य के मुद्दों और कीटों का पता लगाने के लिए उन्नत AI (CNN)।',
    weatherInfo: 'जलवायु लचीलापन',
    weatherInfoDesc: 'एकीकृत मिट्टी का पीएच संकेतक और जलवायु लचीलापन डेटा।',
    advisoryHistory: 'विश्लेषण इतिहास',
    addListing: 'डेटा जोड़ें',
    crop: 'फसल',
    quantity: 'अनुमानित उपज',
    unit: 'इकाई',
    price: 'बाजार मूल्य',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    getAdvice: 'पूर्वानुमान प्राप्त करें',
    season: 'मौसम',
    uploadImage: 'छवि अपलोड करें',
    submit: 'विश्लेषण करें',
    diagnosing: 'प्रसंस्करण...',
    contactUs: 'संपर्क करें',
    contactName: 'नाम',
    contactMessage: 'संदेश',
    send: 'भेजें',
    dateLabel: 'तारीख',
    temperatureLabel: 'तापमान',
    humidityLabel: 'आर्द्रता',
    weatherLabel: 'मौसम',
    searchCity: 'क्षेत्र दर्ज करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    update: 'अपडेट करें',
    loading: 'लोड हो रहा है...',
    search: 'खोज',
    feelsLikeLabel: 'नमी',
    windLabel: 'हवा',
    foggy: 'कोहरा',
  },
  gu: {
    languageCode: 'gu',
    diagnosisLabel: 'વિશ્લેષણ',
    adviceLabel: 'ભલામણ',
    confidenceLabel: 'મોડેલ વિશ્વાસ',
    appName: 'Geospatial AI',
    tagline: 'રામગઢ એન્જિનિયરિંગ કોલેજ - ઇગ્નીશન આઇડિએટર્સ',
    welcome: 'સેટેલાઇટ ઇમેજરી અને એડવાન્સ્ડ AI નો ઉપયોગ કરીને ભારતીય કૃષિમાં વધારો',
    dashboard: 'ડેશબોર્ડ',
    advisory: 'ઉપજ અને પૂરની આગાહી',
    market: 'રીઅલ-ટાઇમ મોનીટરીંગ',
    diagnosis: 'પાક આરોગ્ય (AI)',
    contact: 'સંપર્ક',
    signOut: 'સાઇન આઉટ',
    signIn: 'સાઇન ઇન',
    signUp: 'સાઇન અપ',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
    fullName: 'પૂરું નામ',
    location: 'સ્થાન',
    alreadyHaveAccount: 'શું તમારી પાસે પહેલેથી ખાતું છે?',
    dontHaveAccount: 'શું તમારી પાસે ખાતું નથી?',
    checkEmail: 'કૃપા કરીને ચકાસણી લિંક માટે તમારો ઇમેઇલ તપાસો',
    getStarted: 'શરૂ કરો',
    learnMore: 'વધુ જાણો',
    features: 'લક્ષણો',
    aiAdvisory: 'ઉપજ અને પૂરની આગાહી',
    aiAdvisoryDesc: 'પૂરના નિર્ણયો અને ઉપજની આગાહી માટે સે Sentinel અને RISAT ડેટાનો ઉપયોગ કરે છે.',
    marketLinkage: 'રીઅલ-ટાઇમ મોનીટરીંગ',
    marketLinkageDesc: 'સતત ક્ષેત્ર નિરીક્ષણ માટે સેટેલાઇટ છબી વિશ્લેષણ.',
    cropDiagnosis: 'જીવાત અને રોગની તપાસ',
    cropDiagnosisDesc: 'પાકના સ્વાસ્થ્ય સમસ્યાઓ અને જીવાતોને શોધવા માટે અદ્યતન AI (CNN).',
    weatherInfo: 'આબોહવા સ્થિતિસ્થાપકતા',
    weatherInfoDesc: 'સંકલિત જમીન pH સૂચક અને આબોહવા સ્થિતિસ્થાપકતા ડેટા.',
    advisoryHistory: 'વિશ્લેષણ ઇતિહાસ',
    addListing: 'ડેટા ઉમેરો',
    crop: 'પાક',
    quantity: 'અંદાજિત ઉપજ',
    unit: 'એકમ',
    price: 'બજાર કિંમત',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    getAdvice: 'આગાહી મેળવો',
    season: 'મોસમ',
    uploadImage: 'છબી અપલોડ કરો',
    submit: 'વિશ્લેષણ કરો',
    diagnosing: 'પ્રક્રિયા...',
    contactUs: 'અમારો સંપર્ક કરો',
    contactName: 'નામ',
    contactMessage: 'સંદેશ',
    send: 'મોકલો',
    dateLabel: 'તારીખ',
    temperatureLabel: 'તાપમાન',
    humidityLabel: 'ભેજ',
    weatherLabel: 'હવામાન',
    searchCity: 'પ્રદેશ દાખલ કરો',
    edit: 'સંપાદિત કરો',
    delete: 'કાઢી નાખો',
    update: 'અપડેટ કરો',
    loading: 'લોડ કરી રહ્યું છે...',
    search: 'શોધો',
    feelsLikeLabel: 'ભેજ',
    windLabel: 'પવન',
    foggy: 'ધુમ્મસ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[language] as { [key: string]: string };
    return translation[key] || translations.en[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};